### ISSUE TITLE
Display analytics stuff from #38 in backend

### ISSUE THREAD

**Issue by muellerjonas** [we-loview/loview-frontend#41]

**Comment by muellerjonas** [comment]
Relevant endpoints:

'/stats/users_with_most_location_data' (this is slow because of the DB)
'/stats/number_of_locations'
'/stats/number_of_users'

**Comment by muellerjonas** [comment]
Also:
/stats/correlation_age_flirt_interests and
/stats/correlation_age_flirt_interests?split_genders=True

**Comment by li1** [comment]
update: work on this in `analysis` branch, `/correlation_*` done
also: clean up

**Comment by li1** [comment]
(note to self: rest is done as well)

**Comment by li1** [comment]
number_of_users_with_location_data done
