### ISSUE TITLE
Hotspots: Show # of users at specific hours, aggregated on neighborhoods

### ISSUE THREAD

**Issue by muellerjonas** [we-loview/loview-frontend#57]
There is a REST endpoint for this: ```/stats/locations_hours_districts```
There is also a sample JSON for debugging purposes (so it doesn't take too much time) in the backend in ```examples/geoanalysis_all_locations_for_debug.json``` (or also in our Slack channel, posted Jan. 14th)

**Comment by FelixSchwarzmeier** [comment]
Currently out of scope.
